# Usamos fpm para usarla en conjunto con NGINX
FROM php:8.2-fpm

# Actualizamos el container e instalamos dependencias
RUN apt-get update \
    && apt-get install -y --no-install-recommends\
        git \
        unzip \
        libpq-dev \
        libzip-dev \
        libpng-dev \
        libxml2-dev \
        libonig-dev \
        libcurl4-openssl-dev \
        libsqlite3-dev \
        libjpeg-dev \
        libfreetype-dev \
    && rm -rf /var/lib/apt/lists/*

# extensiones de php requeridas.

RUN docker-php-ext-install \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    sockets 

RUN docker-php-ext-install zip

RUN docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install gd

# Instalamos composer 2.7.5 (mismo de magento)
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.7.5
    
# Define el directorio de trabajo dentro del contenedor
RUN usermod -u 1000 www-data && groupmod -g 1000 www-data
WORKDIR /var/www
USER www-data

# Por defecto, el contenedor FPM expone el puerto 9000
EXPOSE 9000

# El comando por defecto es mantener el proceso FPM corriendo
CMD ["php-fpm"]